# Generated by Django 4.1.7 on 2024-03-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenHouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='name',
            field=models.CharField(default='Blank School', max_length=30),
        ),
    ]
