# Generated by Django 4.1.7 on 2024-03-15 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GreenHouse', '0002_school_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='people',
        ),
        migrations.AddField(
            model_name='extendedusermodel',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GreenHouse.school'),
        ),
    ]
