# Generated by Django 4.1.7 on 2024-03-24 17:53

import colorfield.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenHouse', '0003_remove_school_people_extendedusermodel_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='leafChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None)),
            ],
        ),
        migrations.CreateModel(
            name='plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Plantie', max_length=30)),
                ('type', models.CharField(default='', max_length=30)),
                ('idealTemp', models.IntegerField(default=70)),
                ('idealMoisture', models.IntegerField(default=70)),
                ('idealSoilMoisture', models.IntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='plantHeights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(default=50)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
        ),
        migrations.RemoveField(
            model_name='extendedusermodel',
            name='school',
        ),
        migrations.AddField(
            model_name='extendedusermodel',
            name='role',
            field=models.CharField(default='Student', max_length=30),
        ),
        migrations.CreateModel(
            name='quandrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidity', models.IntegerField(default=40)),
                ('temperature', models.IntegerField(default=40)),
                ('acidity', models.IntegerField(default=40)),
                ('soil_moisture', models.IntegerField(default=40)),
                ('arduino_status', models.BooleanField(default=False)),
                ('plants', models.ManyToManyField(to='GreenHouse.plant')),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='heightUpdates',
            field=models.ManyToManyField(to='GreenHouse.plantheights'),
        ),
        migrations.CreateModel(
            name='leaf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('healthy', models.BooleanField(default=True)),
                ('plant_updates', models.ManyToManyField(to='GreenHouse.leafchange')),
            ],
        ),
        migrations.CreateModel(
            name='box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_num_plants', models.IntegerField(default=20)),
                ('plants_occupied', models.IntegerField(default=0)),
                ('health_rating', models.IntegerField(default=80)),
                ('plant_types', models.IntegerField(default=5)),
                ('temp_avg', models.IntegerField(default=80)),
                ('humidity_avg', models.IntegerField(default=80)),
                ('quandrants', models.ManyToManyField(to='GreenHouse.quandrant')),
            ],
        ),
        migrations.AddField(
            model_name='school',
            name='boxes',
            field=models.ManyToManyField(to='GreenHouse.box'),
        ),
    ]
